Update 2022 - Legiones Astartes.cat
BSData/horus-heresy pull request #2097
Opened 2022-07-08 07:07 UTC by Toreador13

Cleaned up and completed Assault and Despoiler squads. Fixed Toxin Bombs and Dark Channeling so they would work.

Added some more groups entries for Achean Force weapons

2022-07-08 07:13 UTC, Toreador13 commented
Ugh, not sure why this one is so messy. I cleaned up the Sgts and made their options flatter, so that is why so many deletes, not sure what else is going on there. Did a lot of cleanup and added all the legion special options..

2022-07-08 11:26 UTC, nstephenh commented
This one's messy because you don't have my changes. Try merging in from master first.

2022-07-08 15:07 UTC, Toreador13 commented
I'll try that later tonight. Thought I had them when I started. I'll give it another go.

2022-07-09 20:28 UTC, nstephenh requested changes
Looks like you've completely deleted the Legiones Astartes file here...

EDIT: These were my review marks from my first review, but now the file appears completely gone.

2022-07-09 20:34 UTC, Toreador13 commented on 2022 - Legiones Astartes.cat
> +<<<<<<< Updated upstream
I may just start over again. I looked at that also and it seemed weird, and when I opened the file It seemed to have my changes. I think I may close this, and start over. Maybe just get master again and make my changes again.

2022-07-09 20:34 UTC, Toreador13 commented
Closing because something is entirely wrong with this.

2022-07-09 20:34 UTC, closed without merging