Leviathon
BSData/horus-heresy pull request #2118
Opened 2022-07-18 00:51 UTC by revivedtitan

## Added Units
Leviathon Dreadnought
![Leviathan](https://user-images.githubusercontent.com/9825262/179431857-2dd6e149-52aa-4b8f-aad2-3719649d3c42.png)
Please upload a roster do demonstrate your changes.

2022-07-18 11:54 UTC, nstephenh requested changes

2022-07-18 11:54 UTC, nstephenh commented on 2022 - Legiones Astartes.cat
> +            <rule id="c2d0-9f6b-7652-c785" name="Move Through Cover" publicationId="e77a-823a-da94-16b9" page="243" hidden="false">
These should still be rules links, unless they are specific only to the leviathan. I know at least hammer of wrath and dreadnought talon are.

2022-07-18 11:54 UTC, nstephenh commented on 2022 - Legiones Astartes.cat
> +                <selectionEntry id="77eb-0040-30ff-2f20" name="Phosphex Discharger" hidden="false" collective="false" import="true" type="upgrade">
Link to the shared selection entry of this option. If it doesn't exist already, create it as a shared selection entry.

2022-07-18 15:27 UTC, revivedtitan commented
Made the changes to point to rules, selections, and wargear links

2022-07-19 13:02 UTC, nstephenh approved these changes

2022-07-19 13:06 UTC, merged