Toreador13   nl   boo  galoo
BSData/horus-heresy pull request #2231
Opened 2022-08-21 06:48 UTC by Toreador13

WS boogaloo!

Split out White Scar units and completed them including Exemplary and Legacy. Finished Jaghatai. 

Removed units from LA file. 

Found some of the basic equipment on Destroyers was not there, added it.

2022-08-21 11:35 UTC, UrsinePatriarch requested changes
Would request that any Warlord Traits in the WS catalog are changed to the WLT profile rather than rules.
What's going on with the Angel's Tears changes over around 9196? Is that just BS goin odd cause you deleted things and it replaced them? Just checking to be sure.
Can't say all of it is 100% correct, but I'll trust you on this and make edits later if anything turns out to be wrong.

2022-08-21 16:18 UTC, alphalas commented
The tears shit is probably because I deleted it in mine and that one's already been merged

2022-08-22 04:03 UTC, Toreador13 commented
The one Warlord trait changed to profile. 

I didn't touch anything with Blood Angels.

2022-08-22 19:22 UTC, UrsinePatriarch approved these changes

2022-08-22 19:23 UTC, merged